import { GEMINI_CONFIG } from "./config";

/**
 * Server-only Gemini API transport client.
 * Calls Google Generative AI REST endpoint directly without bloated third-party SDK dependencies.
 */
export async function callGeminiApi(
  systemInstruction: string,
  userPrompt: string,
  responseSchema?: Record<string, unknown>
): Promise<string> {
  if (!GEMINI_CONFIG.isConfigured()) {
    // Graceful fallback for local development without live API keys
    return JSON.stringify({
      intent: "ask_question",
      confidence: 0.95,
      extractedParameters: {
        topic: "General Tax Help (API Key Not Configured)",
      },
      missingRequiredFields: [],
    });
  }

  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_CONFIG.modelName}:generateContent?key=${GEMINI_CONFIG.apiKey}`;

  const payload: Record<string, unknown> = {
    systemInstruction: {
      parts: [{ text: systemInstruction }],
    },
    contents: [
      {
        role: "user",
        parts: [{ text: userPrompt }],
      },
    ],
    generationConfig: {
      temperature: GEMINI_CONFIG.temperature,
      maxOutputTokens: GEMINI_CONFIG.maxOutputTokens,
      responseMimeType: responseSchema ? "application/json" : "text/plain",
    },
  };

  const response = await fetch(endpoint, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error("[GEMINI_API_ERROR]", response.status, errorText);
    throw new Error(`Gemini API responded with status ${response.status}`);
  }

  const data = await response.json();
  const textOutput = data?.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!textOutput) {
    throw new Error("No response generated by Gemini model.");
  }

  return textOutput;
}
