import { GEMINI_CONFIG } from "./config";

type GeminiMockHandler = (
  systemInstruction: string,
  userPrompt: string,
  responseSchema?: Record<string, unknown>
) => Promise<string> | string;

let activeMockHandler: GeminiMockHandler | null = null;

/**
 * Test helper to safely mock Gemini responses in automated test suites.
 * Avoids any live network requests during tests.
 */
export function setGeminiMockHandler(handler: GeminiMockHandler | null): void {
  activeMockHandler = handler;
}

/**
 * Server-only Gemini API transport client.
 * Calls Google Generative AI REST endpoint directly without bloated third-party SDK dependencies.
 * Never exposes API keys to client bundles or public endpoints.
 */
export async function callGeminiApi(
  systemInstruction: string,
  userPrompt: string,
  responseSchema?: Record<string, unknown>
): Promise<string> {
  // 1. Check for active test mock handler first
  if (activeMockHandler) {
    return await activeMockHandler(systemInstruction, userPrompt, responseSchema);
  }

  // 2. Offline / Unconfigured Fallback
  if (!GEMINI_CONFIG.isConfigured()) {
    if (responseSchema) {
      return JSON.stringify({
        intent: "GENERAL_TAX_QUESTION",
        confidence: 0.9,
        calculatorType: "income_tax",
        extractedParameters: {
          taxYear: 2025,
          filingStatus: "single",
        },
        missingRequiredFields: [],
      });
    }

    return (
      "I am your TaxAIHelp educational assistant. Our deterministic engine computes official IRS progressive tax formulas. " +
      "You can ask conceptual questions or use our interactive calculators below."
    );
  }

  // 3. Live Google Generative AI REST Endpoint
  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_CONFIG.modelName}:generateContent?key=${GEMINI_CONFIG.apiKey}`;

  const payload: Record<string, unknown> = {
    systemInstruction: {
      parts: [{ text: systemInstruction }],
    },
    contents: [
      {
        role: "user",
        parts: [{ text: userPrompt }],
      },
    ],
    generationConfig: {
      temperature: GEMINI_CONFIG.temperature,
      maxOutputTokens: GEMINI_CONFIG.maxOutputTokens,
      responseMimeType: responseSchema ? "application/json" : "text/plain",
    },
  };

  const response = await fetch(endpoint, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error("[GEMINI_API_ERROR]", response.status, errorText);
    throw new Error(`Gemini API responded with status ${response.status}`);
  }

  const data = await response.json();
  const textOutput = data?.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!textOutput) {
    throw new Error("No response generated by Gemini model.");
  }

  return textOutput;
}
